const glasses = [
    {
        id: 0,
        name: "Vincent Chase",
        logoImg: "Logo/Vincent-Chase.png",
        productType: "eyeglasses",
        status: "new",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Blue",
                colorPallet: "#0000ff",
                templeColour: ["Gunmetal", "Blue"],
                templeColorPallet: ["#b87332", "#0000ff"],
                colorTypes: "Normal",
                src: [
                    "Front/Gunmetal-Full-Rim-Aviator-Eyeglasses.png",
                    "Side/Gunmetal-Full-Rim-Aviator-Eyeglasses.png",
                    "Else/Gunmetal-Full-Rim-Aviator-Eyeglasses1.png",
                    "Else/Gunmetal-Full-Rim-Aviator-Eyeglasses2.png",
                    "Else/Gunmetal-Full-Rim-Aviator-Eyeglasses3.png",
                    "Else/Gunmetal-Full-Rim-Aviator-Eyeglasses4.png",
                    "Person/Gunmetal-Full-Rim-Aviator-Eyeglasses1.png",
                    "Person/Gunmetal-Full-Rim-Aviator-Eyeglasses2.png",
                    "Person/Gunmetal-Full-Rim-Aviator-Eyeglasses3.png",
                    "Person/Gunmetal-Full-Rim-Aviator-Eyeglasses4.png",
                ],
                objectSrc: "Objects/Gunmetal-Full-Rim-Aviator-Eyeglasses.glb",
                availableItems: 20,
            },
            {
                index: 1,
                colorName: "Silver",
                colorPallet: "#c0c0c0",
                templeColour: ["Silver"],
                templeColorPallet: ["#c0c0c0"],
                colorTypes: "Normal",
                src: [
                    "Front/Silver-Full-Rim-Aviator-Eyeglasses.png",
                    "Side/Silver-Full-Rim-Aviator-Eyeglasses.png",
                    "Else/Silver-Full-Rim-Aviator-Eyeglasses1.png",
                    "Else/Silver-Full-Rim-Aviator-Eyeglasses2.png",
                    "Else/Silver-Full-Rim-Aviator-Eyeglasses3.png",
                    "Else/Silver-Full-Rim-Aviator-Eyeglasses4.png",
                    "Person/Gunmetal-Full-Rim-Aviator-Eyeglasses1.png",
                    "Person/Gunmetal-Full-Rim-Aviator-Eyeglasses2.png",
                    "Person/Gunmetal-Full-Rim-Aviator-Eyeglasses3.png",
                    "Person/Gunmetal-Full-Rim-Aviator-Eyeglasses4.png",
                ],
                objectSrc: "Objects/Silver-Full-Rim-Aviator-Eyeglasses.glb",
                availableItems: 20,
            },
        ],
        price: "$20.16",
        gender: "both",
        frameShape: "Aviator",
        frameSize: "Wide",
        frameType: "Full Rim",
        modelNo: "VC E13625",
        frameWidth: "138 mm",
        frameDimensions: "54-16-145",
        weight: "16 gm",
        weightGroup: "Light",
        material: "Stainless Steel",
        frameStyle: "Standard",
        gender: "Any",
        height: "47 mm",
    },
    {
        id: 1,
        name: "Lenskart Air",
        logoImg: "Logo/Lenskart-Air.png",
        productType: "eyeglasses",
        status: "new",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Maroon",
                colorPallet: "#800000",
                templeColour: ["Maroon"],
                templeColorPallet: ["#800000"],
                src: [
                    "Front/Maroon-Full-Rim-Square-Eyeglasses.png",
                    "Side/Maroon-Full-Rim-Square-Eyeglasses.png",
                    "Else/Maroon-Full-Rim-Square-Eyeglasses1.png",
                    "Else/Maroon-Full-Rim-Square-Eyeglasses2.png",
                    "Else/Maroon-Full-Rim-Square-Eyeglasses3.png",
                    "Else/Maroon-Full-Rim-Square-Eyeglasses4.png",
                ],
                objectSrc: "",
                availableItems: 20,
            },
            {
                index: 1,
                colorName: "Blue",
                colorPallet: "#0000ff",
                templeColour: ["Blue"],
                templeColorPallet: ["#0000ff"],
                src: [
                    "Front/Blue-Transparent-Full-Rim-Square-Eyeglasses.png",
                    "Side/Blue-Transparent-Full-Rim-Square-Eyeglasses.png",
                    "Else/Blue-Transparent-Full-Rim-Square-Eyeglasses1.png",
                    "Else/Blue-Transparent-Full-Rim-Square-Eyeglasses2.png",
                    "Else/Blue-Transparent-Full-Rim-Square-Eyeglasses3.png",
                    "Else/Blue-Transparent-Full-Rim-Square-Eyeglasses4.png",
                ],
                objectSrc: "",
                availableItems: 20,
            },
        ],
        price: "$20.16",
        gender: "both",
        frameShape: "Square",
        frameSize: "Medium",
        frameType: "Full Rim",
        modelNo: "LA E14361",
        frameWidth: "135 mm",
        frameDimensions: "55-12-145",
        weight: "19 gm",
        weightGroup: "Light",
        material: "TR90",
        frameStyle: "Light-Weight",
        gender: "Any",
        height: "39 mm",
    },
    {
        id: 2,
        name: "Lenskart Air",
        logoImg: "Logo/Lenskart-Air.png",
        productType: "eyeglasses",
        status: "new",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Maroon",
                colorPallet: "#800000",
                templeColour: ["Maroon"],
                templeColorPallet: ["#800000"],
                src: [
                    "Front/Maroon-Full-Rim-Square-Eyeglasses.png",
                    "Side/Maroon-Full-Rim-Square-Eyeglasses.png",
                    "Else/Maroon-Full-Rim-Square-Eyeglasses1.png",
                    "Else/Maroon-Full-Rim-Square-Eyeglasses2.png",
                    "Else/Maroon-Full-Rim-Square-Eyeglasses3.png",
                    "Else/Maroon-Full-Rim-Square-Eyeglasses4.png",
                ],
                objectSrc: "",
                availableItems: 20,
            },
            {
                index: 1,
                colorName: "Blue",
                colorPallet: "#0000ff",
                templeColour: ["Blue"],
                templeColorPallet: ["#0000ff"],
                src: [
                    "Front/Blue-Transparent-Full-Rim-Square-Eyeglasses.png",
                    "Side/Blue-Transparent-Full-Rim-Square-Eyeglasses.png",
                    "Else/Blue-Transparent-Full-Rim-Square-Eyeglasses1.png",
                    "Else/Blue-Transparent-Full-Rim-Square-Eyeglasses2.png",
                    "Else/Blue-Transparent-Full-Rim-Square-Eyeglasses3.png",
                    "Else/Blue-Transparent-Full-Rim-Square-Eyeglasses4.png",
                ],
                objectSrc: "",
                availableItems: 20,
            },
        ],
        price: "$20.16",
        gender: "both",
        frameShape: "Square",
        frameSize: "Medium",
        frameType: "Full Rim",
        modelNo: "LA E14361",
        frameWidth: "135 mm",
        frameDimensions: "55-12-145",
        weight: "19 gm",
        weightGroup: "Light",
        material: "TR90",
        frameStyle: "Light-Weight",
        gender: "Any",
        height: "39 mm",
    },
];

export default glasses;
