const glasses = [
    {
        id: 0,
        name: "Vincent Chase Polarized",
        logoImg: "Logo/Vincent-Chase.png",
        type: "sunglasses",
        status: "new",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Black",
                colorPallet: "#000",
                src: ["Black-Full-Rim-Square-Sunglasses.png", "Black-Full-Rim-Square-Sunglasses.png", "Black-Full-Rim-Square-Sunglasses.png", "Black-Full-Rim-Square-Sunglasses.png", "Black-Full-Rim-Square-Sunglasses.png", "Black-Full-Rim-Square-Sunglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$20.16",
        gender: "both",
        frameShape: "Aviator",
        size: "Narrow",
    },
    {
        id: 1,
        name: "Vincent Chase",
        logoImg: "Logo/Vincent-Chase.png",
        type: "eyeglasses",
        status: "sale",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Black",
                colorPallet: "#000",
                src: ["Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png"],
                availableItems: 20,
            },
            {
                index: 1,
                colorName: "Purple",
                colorPallet: "#800080",
                src: ["Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$15.12",
        salePrice: "$25.22",
        gender: "female",
        frameShape: "Geometric",
        size: "Narrow",
    },
    {
        id: 2,
        name: "Lenskart Air",
        logoImg: "Logo/Lenskart-Air.png",
        type: "eyeglasses",
        status: "sale",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Black",
                colorPallet: "#000",
                src: ["Black-Silver-Full-Rim-Rectangle-Eyeglasses.png", "Black-Silver-Full-Rim-Rectangle-Eyeglasses.png", "Black-Silver-Full-Rim-Rectangle-Eyeglasses.png", "Black-Silver-Full-Rim-Rectangle-Eyeglasses.png", "Black-Silver-Full-Rim-Rectangle-Eyeglasses.png", "Black-Silver-Full-Rim-Rectangle-Eyeglasses.png"],
                availableItems: 20,
            },
            {
                index: 1,
                colorName: "Silver",
                colorPallet: "#c0c0c0",
                src: ["Black-Silver-Full-Rim-Rectangle-Eyeglasses.png", "Black-Silver-Full-Rim-Rectangle-Eyeglasses.png", "Black-Silver-Full-Rim-Rectangle-Eyeglasses.png", "Black-Silver-Full-Rim-Rectangle-Eyeglasses.png", "Black-Silver-Full-Rim-Rectangle-Eyeglasses.png", "Black-Silver-Full-Rim-Rectangle-Eyeglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$15.12",
        salePrice: "$25.22",
        gender: "kids",
        frameShape: "Square",
        size: "Narrow",
    },
    {
        id: 3,
        name: "Vincent Chase Polarized",
        logoImg: "Logo/Vincent-Chase.png",
        type: "sunglasses",
        status: "top",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Brown",
                colorPallet: "#a52a2a",
                src: ["Brown-Tortoise-Full-Rim-Round-Sunglasses.png", "Brown-Tortoise-Full-Rim-Round-Sunglasses.png", "Brown-Tortoise-Full-Rim-Round-Sunglasses.png", "Brown-Tortoise-Full-Rim-Round-Sunglasses.png", "Brown-Tortoise-Full-Rim-Round-Sunglasses.png", "Brown-Tortoise-Full-Rim-Round-Sunglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$20.16",
        frameShape: "Round",
        gender: "male",
        size: "Narrow",
    },
    {
        id: 4,
        name: "John Jacobs",
        logoImg: "Logo/John-Jacobs.png",
        type: "sunglasses",
        status: "sale",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Gold",
                colorPallet: "#ffd700",
                src: ["Gold-Tortoise-Full-Rim-Rectangle-Sunglasses.png", "Gold-Tortoise-Full-Rim-Rectangle-Sunglasses.png", "Gold-Tortoise-Full-Rim-Rectangle-Sunglasses.png", "Gold-Tortoise-Full-Rim-Rectangle-Sunglasses.png", "Gold-Tortoise-Full-Rim-Rectangle-Sunglasses.png", "Gold-Tortoise-Full-Rim-Rectangle-Sunglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$75.65",
        salePrice: "$88.26",
        gender: "female",
        frameShape: "Round",
        size: "Narrow",
    },
    {
        id: 5,
        name: "John Jacobs",
        logoImg: "Logo/John-Jacobs.png",
        type: "sunglasses",
        status: "new",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Grey",
                colorPallet: "#808080",
                src: ["Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$50.43",
        gender: "kids",
        frameShape: "Aviator",
        size: "Narrow",
    },
    {
        id: 6,
        name: "John Jacobs",
        logoImg: "Logo/John-Jacobs.png",
        type: "sunglasses",
        status: "top",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Grey",
                colorPallet: "#808080",
                src: ["Grey-Full-Rim-Wayfarer-Sunglasses.png", "Grey-Full-Rim-Wayfarer-Sunglasses.png", "Grey-Full-Rim-Wayfarer-Sunglasses.png", "Grey-Full-Rim-Wayfarer-Sunglasses.png", "Grey-Full-Rim-Wayfarer-Sunglasses.png", "Grey-Full-Rim-Wayfarer-Sunglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$50.43",
        gender: "male",
        frameShape: "Hexagon",
        size: "Narrow",
    },
    {
        id: 7,
        name: "Lenskart Air Computer Glasses",
        logoImg: "Logo/Lenskart-Air.png",
        type: "eyeglasses",
        status: "top",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Grey",
                colorPallet: "#808080",
                src: ["Grey-Transparent-Full-Rim-Round-Eyeglasses.png", "Grey-Transparent-Full-Rim-Round-Eyeglasses.png", "Grey-Transparent-Full-Rim-Round-Eyeglasses.png", "Grey-Transparent-Full-Rim-Round-Eyeglasses.png", "Grey-Transparent-Full-Rim-Round-Eyeglasses.png", "Grey-Transparent-Full-Rim-Round-Eyeglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$21.43",
        gender: "female",
        frameShape: "Club Master",
        size: "Narrow",
    },
    {
        id: 8,
        name: "Lenskart Air Computer Glasses",
        logoImg: "Logo/Lenskart-Air.png",
        type: "eyeglasses",
        status: "top",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Black",
                colorPallet: "#000",
                src: ["Black-Full-Rim-Rectangle-Eyeglasses.png", "Black-Full-Rim-Rectangle-Eyeglasses.png", "Black-Full-Rim-Rectangle-Eyeglasses.png", "Black-Full-Rim-Rectangle-Eyeglasses.png", "Black-Full-Rim-Rectangle-Eyeglasses.png", "Black-Full-Rim-Rectangle-Eyeglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$21.43",
        gender: "kids",
        frameShape: "Round",
        size: "Narrow",
    },
    {
        id: 9,
        name: "Vincent Chase",
        logoImg: "Logo/Vincent-Chase.png",
        type: "eyeglasses",
        status: "top",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Maroon",
                colorPallet: "#800000",
                src: ["Maroon-Full-Rim-Square-Eyeglasses.png", "Maroon-Full-Rim-Square-Eyeglasses.png", "Maroon-Full-Rim-Square-Eyeglasses.png", "Maroon-Full-Rim-Square-Eyeglasses.png", "Maroon-Full-Rim-Square-Eyeglasses.png", "Maroon-Full-Rim-Square-Eyeglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$15.12",
        gender: "male",
        frameShape: "Square",
        size: "Narrow",
    },
    {
        id: 10,
        name: "Vincent Chase",
        logoImg: "Logo/Vincent-Chase.png",
        type: "eyeglasses",
        status: "top",
        colorTypes: "Transparent",
        colors: [
            {
                index: 0,
                colorName: "Blue",
                colorPallet: "#0000ff",
                src: ["Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$15.12",
        gender: "female",
        frameShape: "Rectangle",
        size: "Narrow",
    },
    {
        id: 11,
        name: "Vincent Chase",
        logoImg: "Logo/Vincent-Chase.png",
        type: "sunglasses",
        status: "new",
        colorTypes: "Matte",
        colors: [
            {
                index: 0,
                colorName: "Black",
                colorPallet: "#000",
                src: ["Matte-Black-Full-Rim-Wayfarer-Sunglasses.png", "Matte-Black-Full-Rim-Wayfarer-Sunglasses.png", "Matte-Black-Full-Rim-Wayfarer-Sunglasses.png", "Matte-Black-Full-Rim-Wayfarer-Sunglasses.png", "Matte-Black-Full-Rim-Wayfarer-Sunglasses.png", "Matte-Black-Full-Rim-Wayfarer-Sunglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$15.12",
        gender: "male",
        frameShape: "Cat Eye",
        size: "Narrow",
    },
    {
        id: 12,
        name: "John Jacobs",
        logoImg: "Logo/John-Jacobs.png",
        type: "sunglasses",
        status: "new",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Grey",
                colorPallet: "#808080",
                src: ["Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$50.43",
        gender: "kids",
        frameShape: "Rectangle",
        size: "Narrow",
    },
    {
        id: 13,
        name: "John Jacobs",
        logoImg: "Logo/John-Jacobs.png",
        type: "sunglasses",
        status: "new",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Grey",
                colorPallet: "#808080",
                src: ["Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$50.43",
        gender: "male",
        frameShape: "Wayfarer",
        size: "Narrow",
    },
    {
        id: 14,
        name: "John Jacobs",
        logoImg: "Logo/John-Jacobs.png",
        type: "sunglasses",
        status: "new",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                colorName: "Grey",
                colorPallet: "#808080",
                src: ["Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png", "Grey-Full-Rim-Hexagonal-Sunglasses.png"],
                availableItems: 20,
            },
        ],
        price: "$50.43",
        gender: "female",
        frameShape: "Hexagon",
        size: "Narrow",
    },
    {
        id: 15,
        name: "Vincent Chase",
        logoImg: "Logo/Vincent-Chase.png",
        type: "eyeglasses",
        status: "sale",
        colors: [
            {
                index: 0,
                colorName: "Blue",
                colorPallet: "#0000ff",
                src: ["Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png"],
                availableItems: 20,
            },
        ],
        colorTypes: "Transparent",
        price: "$15.12",
        gender: "kids",
        frameShape: "Hexagon",
        size: "Narrow",
    },
    {
        id: 16,
        name: "Vincent Chase",
        logoImg: "Logo/Vincent-Chase.png",
        type: "eyeglasses",
        status: "sale",
        colors: [
            {
                index: 0,
                colorName: "Blue",
                colorPallet: "#0000ff",
                src: ["Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png"],
                availableItems: 20,
            },
        ],
        colorTypes: "Transparent",
        price: "$15.12",
        gender: "male",
        frameShape: "Hexagon",
        size: "Narrow",
    },
    {
        id: 17,
        name: "Vincent Chase",
        logoImg: "Logo/Vincent-Chase.png",
        type: "eyeglasses",
        status: "sale",
        colors: [
            {
                index: 0,
                colorName: "Blue",
                colorPallet: "#0000ff",
                src: ["Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png", "Blue-Transparent-Full-Rim-Rectangle-Eyeglasses.png"],
                availableItems: 20,
            },
        ],
        colorTypes: "Transparent",
        price: "$15.12",
        gender: "female",
        frameShape: "Rectangle",
        size: "Narrow",
    },
    {
        id: 18,
        name: "Vincent Chase",
        logoImg: "Logo/Vincent-Chase.png",
        status: "new",
        colors: [
            {
                index: 0,
                colorName: "Black",
                colorPallet: "#000",
                src: ["Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png"],
                availableItems: 20,
            },
            {
                index: 1,
                colorName: "Purple",
                colorPallet: "#800080",
                src: ["Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png", "Black-Purple-Full-Rim-Square-Eyeglasses.png"],
                availableItems: 20,
            },
        ],
        colorTypes: "Normal",
        type: "eyeglasses",
        price: "$15.12",
        salePrice: "$25.22",
        gender: "kids",
        frameShape: "Geometric",
        size: "Narrow",
    },
];

export default glasses;
