const glasses = [
    {
        id: 0,
        name: "Vincent Chase",
        logoImg: "Logo/Vincent-Chase.png",
        productType: "eyeglasses",
        status: "new",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                color: "#0000ff",
                templeColor: ["#b87332", "#0000ff"],
                colorTypes: "Normal",
                status: "new",
                name: "Gunmetal Full Rim Aviator Eyeglasses",
                src: [
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/Gunmetal/Gunmetal-Full-Rim-Aviator-Eyeglasses.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/Gunmetal/1.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/Gunmetal/2.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/Gunmetal/3.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/Gunmetal/4.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/Gunmetal/5.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/People/Gunmetal-Full-Rim-Aviator-Eyeglasses1.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/People/Gunmetal-Full-Rim-Aviator-Eyeglasses2.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/People/Gunmetal-Full-Rim-Aviator-Eyeglasses3.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/People/Gunmetal-Full-Rim-Aviator-Eyeglasses4.png",
                ],
                objectSrc:
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/Gunmetal/Gunmetal-Full-Rim-Aviator-Eyeglasses.usdz",
                availableItems: 20,
            },
            {
                index: 1,
                color: "#c0c0c0",
                templeColor: ["#c0c0c0"],
                colorTypes: "Normal",
                status: "new",
                name: "Silver Full Rim Aviator Eyeglasses",
                src: [
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/Silver/Silver-Full-Rim-Aviator-Eyeglasses.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/Silver/1.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/Silver/2.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/Silver/3.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/Silver/4.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/Silver/5.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/People/Gunmetal-Full-Rim-Aviator-Eyeglasses1.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/People/Gunmetal-Full-Rim-Aviator-Eyeglasses2.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/People/Gunmetal-Full-Rim-Aviator-Eyeglasses3.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/People/Gunmetal-Full-Rim-Aviator-Eyeglasses4.png",
                ],
                objectSrc:
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Gunmetal-Silver-People-VC E13625/Silver/Silver-Full-Rim-Aviator-Eyeglasses.usdz",
                availableItems: 20,
            },
        ],
        price: 20.16,
        frameShape: "Aviator",
        frameSize: "Wide",
        frameType: "Full Rim",
        modelNo: "VC E13625",
        frameWidth: "138 mm",
        frameDimensions: "54-16-145",
        weight: "16 gm",
        weightGroup: "Light",
        material: "Stainless Steel",
        frameStyle: "Standard",
        salePercent: 0,
        gender: "Any",
        height: "47 mm",
    },
    {
        id: 1,
        name: "Lenskart Air",
        logoImg: "Logo/Lenskart-Air.png",
        productType: "eyeglasses",
        status: "new",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                color: "#800000",
                templeColor: ["#800000"],
                colorTypes: "Normal",
                status: "new",
                name: "Maroon Full Rim Square Eyeglasses",
                src: [
                    "Full-Rim/Square/Eyeglasses/Lenskart Air/Blue-Transparent-Maroon-LA E14361/Maroon/Maroon-Full-Rim-Square-Eyeglasses.png",
                    "Full-Rim/Square/Eyeglasses/Lenskart Air/Blue-Transparent-Maroon-LA E14361/Maroon/1.png",
                    "Full-Rim/Square/Eyeglasses/Lenskart Air/Blue-Transparent-Maroon-LA E14361/Maroon/2.png",
                    "Full-Rim/Square/Eyeglasses/Lenskart Air/Blue-Transparent-Maroon-LA E14361/Maroon/3.png",
                    "Full-Rim/Square/Eyeglasses/Lenskart Air/Blue-Transparent-Maroon-LA E14361/Maroon/4.png",
                    "Full-Rim/Square/Eyeglasses/Lenskart Air/Blue-Transparent-Maroon-LA E14361/Maroon/5.png",
                ],
                objectSrc: "",
                availableItems: 20,
            },
            {
                index: 1,
                color: "#0000ff",
                templeColor: ["#0000ff"],
                colorTypes: "Normal",
                status: "new",
                name: "Blue Transparent Full Rim Square Eyeglasses",
                src: [
                    "Full-Rim/Square/Eyeglasses/Lenskart Air/Blue-Transparent-Maroon-LA E14361/Blue-Transparent/Blue-Transparent-Full-Rim-Square-Eyeglasses.png",
                    "Full-Rim/Square/Eyeglasses/Lenskart Air/Blue-Transparent-Maroon-LA E14361/Blue-Transparent/1.png",
                    "Full-Rim/Square/Eyeglasses/Lenskart Air/Blue-Transparent-Maroon-LA E14361/Blue-Transparent/2.png",
                    "Full-Rim/Square/Eyeglasses/Lenskart Air/Blue-Transparent-Maroon-LA E14361/Blue-Transparent/3.png",
                    "Full-Rim/Square/Eyeglasses/Lenskart Air/Blue-Transparent-Maroon-LA E14361/Blue-Transparent/4.png",
                    "Full-Rim/Square/Eyeglasses/Lenskart Air/Blue-Transparent-Maroon-LA E14361/Blue-Transparent/5.png",
                ],
                objectSrc: "",
                availableItems: 20,
            },
        ],
        price: 20.16,
        frameShape: "Square",
        frameSize: "Medium",
        frameType: "Full Rim",
        modelNo: "LA E14361",
        frameWidth: "135 mm",
        frameDimensions: "55-12-145",
        weight: "19 gm",
        weightGroup: "Light",
        material: "TR90",
        frameStyle: "Light-Weight",
        salePercent: 0,
        gender: "Any",
        height: "39 mm",
    },
    {
        id: 2,
        name: "Lenskart Air",
        logoImg: "Logo/Lenskart-Air.png",
        productType: "eyeglasses",
        status: "sale",
        colorTypes: "Transparent",
        colors: [
            {
                index: 0,
                color: "#f1f1f1",
                templeColor: ["#f1f1f1", "#f1f1f161"],
                colorTypes: "Transparent",
                status: "sale",
                name: "Transparent Full Rim Aviator Eyeglasses",
                src: [
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Black-Transparent-LA E14559/Transparent/Transparent-Full-Rim-Aviator-Eyeglasses.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Black-Transparent-LA E14559/Transparent/1.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Black-Transparent-LA E14559/Transparent/2.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Black-Transparent-LA E14559/Transparent/3.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Black-Transparent-LA E14559/Transparent/4.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Black-Transparent-LA E14559/Transparent/5.png",
                ],
                objectSrc:
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Black-Transparent-LA E14559/Transparent/Transparent-Full-Rim-Aviator-Eyeglasses.glb",
                availableItems: 20,
            },
            {
                index: 1,
                color: "#000",
                templeColor: ["#ffd700", "#000"],
                colorTypes: "Normal",
                status: "sale",
                name: "Black Full Rim Aviator Eyeglasses",
                src: [
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Black-Transparent-LA E14559/Black/Black-Full-Rim-Aviator-Eyeglasses.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Black-Transparent-LA E14559/Black/1.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Black-Transparent-LA E14559/Black/2.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Black-Transparent-LA E14559/Black/3.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Black-Transparent-LA E14559/Black/4.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Black-Transparent-LA E14559/Black/5.png",
                ],
                objectSrc:
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Black-Transparent-LA E14559/Black/Black-Full-Rim-Aviator-Eyeglasses.glb",
                availableItems: 20,
            },
        ],
        price: 20.16,
        frameShape: "Aviator",
        frameSize: "Wide",
        frameType: "Full Rim",
        modelNo: "LA E14559",
        frameWidth: "139 mm",
        frameDimensions: "54-17-150",
        weight: "16 gm",
        weightGroup: "Light",
        material: "TR90",
        frameStyle: "Light-Weight",
        salePercent: 40,
        gender: "Any",
        height: "48 mm",
    },
    {
        id: 3,
        name: "Vincent Chase",
        logoImg: "Logo/Vincent-Chase.png",
        productType: "eyeglasses",
        status: "top",
        colorTypes: "Transparent",
        colors: [
            {
                index: 0,
                color: "gold",
                templeColor: ["gold", "black"],
                colorTypes: "Normal",
                name: "Gold Full Rim Aviator Eyeglasses",
                status: "top",
                src: [
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Gold/Gold-Full-Rim-Aviator-Eyeglasses.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Gold/1.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Gold/2.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Gold/3.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Gold/4.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Gold/5.png",
                ],
                objectSrc:
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Gold/Gold-Full-Rim-Aviator-Eyeglasses.usdz",
                availableItems: 20,
            },
            {
                index: 1,
                color: "silver",
                templeColor: ["silver", "black"],
                colorTypes: "Normal",
                name: "Silver Full Rim Aviator Eyeglasses",
                status: "new",
                src: [
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/Silver-Full-Rim-Aviator-Eyeglasses.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/1.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/2.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/3.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/4.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/5.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/6.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/7.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/8.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/9.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/10.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/11.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/12.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/13.jpg",
                ],
                objectSrc:
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Silver/Silver-Full-Rim-Aviator-Eyeglasses.usdz",
                availableItems: 20,
            },
            {
                index: 2,
                color: "black",
                templeColor: ["black"],
                colorTypes: "Normal",
                name: "Black Full Rim Aviator Eyeglasses",
                status: "new",
                src: [
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Black/Black-Full-Rim-Aviator-Eyeglasses.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Black/1.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Black/2.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Black/3.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Black/4.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Black/5.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Black/6.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Black/7.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Black/8.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Black/9.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Black/10.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Black/11.jpg",
                ],
                objectSrc:
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Black/Black-Full-Rim-Aviator-Eyeglasses.usdz",
                availableItems: 20,
            },
            {
                index: 3,
                color: "blue",
                templeColor: ["blue", "black"],
                colorTypes: "Normal",
                name: "Blue Full Rim Aviator Eyeglasses",
                status: "top",
                src: [
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Blue/Blue-Full-Rim-Aviator-Eyeglasses.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Blue/1.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Blue/2.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Blue/3.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Blue/4.png",
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Blue/5.png",
                ],
                objectSrc:
                    "Full-Rim/Aviator/Eyeglasses/Vincent Chase/Black-Blue-Gold-Silver-VC E13046/Blue/Blue-Full-Rim-Aviator-Eyeglasses.usdz",
                availableItems: 20,
            },
        ],
        price: 20.16,
        frameShape: "Aviator",
        frameSize: "Wide",
        frameType: "Full Rim",
        modelNo: "VC E13046",
        frameWidth: "140 mm",
        frameDimensions: "56-16-145",
        weight: "16 gm",
        weightGroup: "Light",
        material: "Stainless Steel",
        frameStyle: "Standard",
        salePercent: 40,
        gender: "Any",
        height: "47 mm",
    },
    {
        id: 0,
        name: "Vincent Chase",
        logoImg: "Logo/Vincent-Chase.png",
        productType: "eyeglasses",
        status: "new",
        colorTypes: "Normal",
        colors: [
            {
                index: 0,
                color: "Brown",
                templeColor: ["Brown"],
                status: "new",
                colorTypes: "Normal",
                name: "Brown Rimless Aviator Eyeglasses",
                src: [
                    "Rimless/Aviator/Eyeglasses/Vincent Chase/Brown-VC E12421/Brown-Rimless-Aviator-Eyeglasses.png",
                    "Rimless/Aviator/Eyeglasses/Vincent Chase/Brown-VC E12421/1.png",
                    "Rimless/Aviator/Eyeglasses/Vincent Chase/Brown-VC E12421/2.png",
                    "Rimless/Aviator/Eyeglasses/Vincent Chase/Brown-VC E12421/3.png",
                    "Rimless/Aviator/Eyeglasses/Vincent Chase/Brown-VC E12421/4.png",
                    "Rimless/Aviator/Eyeglasses/Vincent Chase/Brown-VC E12421/5.png",
                    "Rimless/Aviator/Eyeglasses/Vincent Chase/Brown-VC E12421/6.jpg",
                    "Rimless/Aviator/Eyeglasses/Vincent Chase/Brown-VC E12421/7.jpg",
                    "Rimless/Aviator/Eyeglasses/Vincent Chase/Brown-VC E12421/8.jpg",
                    "Rimless/Aviator/Eyeglasses/Vincent Chase/Brown-VC E12421/9.jpg",
                ],
                objectSrc:
                    "Rimless/Aviator/Eyeglasses/Vincent Chase/Brown-VC E12421/Brown-Rimless-Aviator-Eyeglasses.usdz",
                availableItems: 20,
            },
        ],
        price: 45.16,
        frameShape: "Aviator",
        frameSize: "Extra Narrow",
        frameType: "Rimless",
        modelNo: "VC E12421",
        frameWidth: "129 mm",
        frameDimensions: "53-16-140",
        weight: "17 gm",
        weightGroup: "Light",
        material: "Stainless Steel",
        frameStyle: "Standard",
        salePercent: 0,
        gender: "Any",
        height: "46 mm",
    },
    {
        id: 0,
        name: "Lenskart Air",
        logoImg: "Logo/Lenskart-Air.png",
        productType: "eyeglasses",
        status: "top",
        colorTypes: "Transparent",
        colors: [
            {
                index: 0,
                color: "#0000ffbd",
                templeColor: ["#0000ffbd"],
                colorTypes: "Transparent",
                status: "top",
                name: "Blue Transparent Full Rim Aviator Eyeglasses",
                src: [
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Blue/Blue-Transparent-Full-Rim-Aviator-Eyeglasses.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Blue/1.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Blue/2.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Blue/3.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Blue/4.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Blue/5.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Blue/6.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Blue/7.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Blue/8.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Blue/9.jpg",
                ],
                objectSrc: "",
                availableItems: 20,
            },
            {
                index: 0,
                color: "#808080bd",
                templeColor: ["#808080bd"],
                colorTypes: "Transparent",
                status: "top",
                name: "Grey Transparent Full Rim Aviator Eyeglasses",
                src: [
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey/Grey-Transparent-Full-Rim-Aviator-Eyeglasses.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey/1.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey/2.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey/3.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey/4.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey/5.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey/6.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey/7.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey/8.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey/9.jpg",
                ],
                objectSrc: "",
                availableItems: 20,
            },
            {
                index: 0,
                color: "#e1e1e1",
                templeColor: ["#e1e1e1"],
                colorTypes: "Transparent",
                status: "top",
                name: "Transparent Full Rim Aviator Eyeglasses",
                src: [
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Transparent/Transparent-Full-Rim-Aviator-Eyeglasses.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Transparent/1.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Transparent/2.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Transparent/3.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Transparent/4.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Transparent/5.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Transparent/6.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Transparent/7.jpg",
                ],
                objectSrc: "",
                availableItems: 20,
            },
            {
                index: 0,
                color: "#dfd7cc",
                templeColor: ["#dfd7cc"],
                colorTypes: "Normal",
                status: "top",
                name: "Violet Green Transparent Full Rim Aviator Eyeglasses",
                src: [
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Violet-Green/Violet-Green-Transparent-Full-Rim-Aviator-Eyeglasses.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Violet-Green/1.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Violet-Green/2.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Violet-Green/3.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Violet-Green/4.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Violet-Green/5.png",
                ],
                objectSrc: "",
                availableItems: 20,
            },
            {
                index: 0,
                color: "#808080",
                templeColor: ["#808080"],
                colorTypes: "Normal",
                status: "top",
                name: "Gunmetal Full Rim Square Eyeglasses",
                src: [
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey-Transparent/Gunmetal-Full-Rim-Square-Eyeglasses.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey-Transparent/1.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey-Transparent/2.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey-Transparent/3.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey-Transparent/4.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey-Transparent/5.png",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey-Transparent/6.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey-Transparent/7.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey-Transparent/8.jpg",
                    "Full-Rim/Aviator/Eyeglasses/Lenskart Air/Blue-Grey-Transparent-Violet-Green-LA E14832/Grey-Transparent/9.jpg",
                ],
                objectSrc: "",
                availableItems: 20,
            },
        ],
        price: 45.16,
        frameShape: "Aviator",
        frameSize: "Extra Wide",
        frameType: "Full Rim",
        modelNo: "LA E14832",
        frameWidth: "142 mm",
        frameDimensions: "55-17-146",
        weight: "16 gm",
        weightGroup: "Light",
        material: "Ultem",
        frameStyle: "Light-Weight",
        salePercent: 0,
        gender: "Any",
        height: "45 mm",
    },
    {
        name: "Vincent Chase",
        logoImg: "Logo/Lenskart-Air.png",
        productType: "eyeglasses",
        status: "sale",
        colorTypes: "Transparent",
        colors: [
            {
                index: 0,
                color: "#b87332",
                templeColor: ["#b87332"],
                colorTypes: "Normal",
                status: "top",
                name: "Gunmetal Full Rim Square Eyeglasses",
                src: [
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Gunmetal/Gunmetal_Full_Rim_Square_Eyeglasses.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Gunmetal/1.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Gunmetal/2.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Gunmetal/3.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Gunmetal/4.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Gunmetal/5.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Gunmetal/6.jpg",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Gunmetal/7.jpg",
                ],
                objectSrc: "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Gunmetal/Gunmetal-Full-Rim-Square-Eyeglasses.usdz",
                availableItems: 20,
            },
            {
                index: 0,
                color: "#c0c0c0",
                templeColor: ["#c0c0c0"],
                colorTypes: "Normal",
                status: "top",
                name: "Silver Full Rim Square Eyeglasses",
                src: [
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Silver/Silver_Full_Rim_Square_Eyeglasses.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Silver/1.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Silver/2.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Silver/3.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Silver/4.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Silver/5.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Silver/6.jpg",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Silver/7.jpg",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Silver/8.jpg",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Silver/9.jpg",
                ],
                objectSrc: "Full-Rim/Square/Eyeglasses/Vincent Chase/Gunmetal-Silver-VC-E12422-M/Silver/Silver_Full_Rim_Square_Eyeglasses.usdz",
                availableItems: 20,
            },
        ],
        price: 95.29,
        frameShape: "Square",
        frameSize: "Medium",
        frameType: "Full Rim",
        modelNo: "VC E12422-M",
        frameWidth: "134 mm",
        frameDimensions: "55-13-145",
        weight: "19 gm",
        weightGroup: "Light",
        material: "Stainless Steel",
        frameStyle: "Standard",
        salePercent: 10,
        gender: "Any",
        height: "45 mm",
    },
    {
        name: "Vincent Chase",
        logoImg: "Logo/Lenskart-Air.png",
        productType: "eyeglasses",
        status: "sale",
        colorTypes: "Transparent",
        colors: [
            {
                index: 0,
                color: "#b87332",
                templeColor: ["#b87332"],
                colorTypes: "Normal",
                status: "top",
                name: "Gunmetal Full Rim Square Eyeglasses",
                src: [
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Gunmetal/Gunmetal_Full_Rim_Square_Eyeglasses.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Gunmetal/1.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Gunmetal/2.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Gunmetal/3.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Gunmetal/4.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Gunmetal/5.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Gunmetal/6.jpg",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Gunmetal/7.jpg",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Gunmetal/8.jpg",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Gunmetal/9.jpg",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Gunmetal/10.jpg",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Gunmetal/11.jpg",
                ],
                objectSrc: "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Gunmetal/Gunmetal_Full_Rim_Square_Eyeglasses.usdz",
                availableItems: 20,
            },
            {
                index: 0,
                color: "#0000ff",
                templeColor: ["#0000ff"],
                colorTypes: "Normal",
                status: "top",
                name: "Silver Full Rim Square Eyeglasses",
                src: [
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Blue/Blue_Full_Rim_Square_Eyeglasses.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Blue/1.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Blue/2.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Blue/3.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Blue/4.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Blue/5.png",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Blue/6.jpg",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Blue/7.jpg",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Blue/8.jpg",
                    "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Blue/9.jpg",
                ],
                objectSrc: "Full-Rim/Square/Eyeglasses/Vincent Chase/Blue-Gunmetal-VC-E12422/Silver/Blue_Full_Rim_Square_Eyeglasses.usdz",
                availableItems: 20,
            },
        ],
        price: 95.29,
        frameShape: "Square",
        frameSize: "Wide",
        frameType: "Full Rim",
        modelNo: "VC E12422",
        frameWidth: "138 mm",
        frameDimensions: "56-14-145",
        weight: "16 gm",
        weightGroup: "Light",
        material: "Stainless Steel",
        frameStyle: "Standard",
        salePercent: 10,
        gender: "Any",
        height: "48 mm",
    },
];

export default glasses;
